### PR TITLE
Fix Client::getTime()

### LINKED ISSUE #298: `Bigcommerce::getTime()` doesn't validate store credentials and returns garbage
### Expected behavior

`\Bigcommerce\Api\Client::getTime()` should fail on invalid store credentials, as [documented](https://github.com/bigcommerce/bigcommerce-api-php/blob/master/src/Bigcommerce/Api/Client.php#L477)

### Actual behavior

[`\Bigcommerce\Api\Client::getTime()`](https://github.com/bigcommerce/bigcommerce-api-php/blob/master/src/Bigcommerce/Api/Client.php#L483) uses `$api_url` instead of `$api_path` so it effectively requests `https://api.bigcommerce.com/time`, which doesn't check for any store credentials.

On top of that, that endpoint returns timestamp in milliseconds, and `getTime()` parses is as seconds, so it returns bogus `DateTime` object

### Steps to reproduce behavior

Run without any prior setup:

```
>>> \Bigcommerce\Api\Client::getTime()
=>  DateTime @1718280499756 {#5814
      date: 56420-02-21 18:49:16.0 +00:00,
    }
```

### PR DESCRIPTION
**Pull request by TomA-R**
## What/Why?
Fixes #298

- Updates Client::getTime() to expect time in milliseconds as that's [the response from /time](https://api.bigcommerce.com/time)
- Adds Client::getStoreTime() which queries https://api.bigcommerce.com/stores/{{storeHash}}/v2/time. That requires authentication so this method can be used to verify that the client is configured correctly
- Update README to reflect changes

## Testing

_**Updated `::getTime()`**_
I've updated the unit test to reflect what's actually returned by the API. Also I've run the steps provided to reproduce this issue, verifying that it no longer happens:

```
php > var_dump(\Bigcommerce\Api\Client::getTime());
php shell code:1:
class DateTime#6 (3) {
  public $date =>
  string(26) "2024-06-13 13:43:56.124000"
  public $timezone_type =>
  int(1)
  public $timezone =>
  string(6) "+00:00"
}
```

_**Added `::getStoreTime()`**_
```
php > var_dump(\Bigcommerce\Api\Client::getStoreTime());
php shell code:1:
class DateTime#7 (3) {
  public $date =>
  string(26) "2024-06-14 09:01:35.000000"
  public $timezone_type =>
  int(1)
  public $timezone =>
  string(6) "+00:00"
}
```

### CODE REVIEW

File: src/Bigcommerce/Api/Client.php [hunk 1]
```diff
@@ -474,19 +474,38 @@ public static function getCustomerLoginToken($id, $redirectUrl = '', $requestIp
...
         $response = self::connection()->get(self::$api_url . '/time');
 
-        if (empty($response)) {
+        if (empty($response) || !is_numeric($response)) {
+            return null;
+        }
+
+        // The response from /time is unix time in milliseconds
+        $seconds = floor($response / 1000);
+        $microseconds = $response % 1000;
```
Comment (filakhtov) [inline src/Bigcommerce/Api/Client.php:491]:
```suggestion
        $milliseconds = $response % 1000;
```

File: test/Unit/Api/ClientTest.php [hunk 2]
```diff
@@ -206,13 +206,32 @@ public function testDeleteResourceDeletesToTheRightPlace()
...
-        $this->assertEquals($now->format('U'), Client::getTime()->format('U'));
+        $this->assertEquals('2024-06-13 13:00:00', Client::getTime()->format('Y-m-d H:i:s'));
+    }
+
+    public function testGetStoreTimeReturnsTheExpectedTime()
+    {
+        $this->connection->expects($this->once())
+            ->method('get')
+            ->with($this->basePath . '/time')
+            ->will($this->returnValue(json_decode('{"time": 1718283600}')));
```
Comment (filakhtov) [inline test/Unit/Api/ClientTest.php:222]:
```suggestion
            ->will($this->returnValue((object)['time' => 1718283600]));
```

**Review by filakhtov — APPROVED** [review]
